# Generated by Django 3.2 on 2021-04-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('section', models.CharField(choices=[('EA', 'Anubhuti Class(EA)'), ('1A', 'AC First Class(1A)'), ('EC', 'Exec. Chair Car(EC)'), ('2A', 'AC 2Tier (2A)'), ('FC', 'First CLass(FC)'), ('3A', 'AC 3 Tier(3A)'), ('3E', 'AC 3Economy (3E)'), ('CC', 'AC Chair car(CC)')], max_length=50)),
                ('concession', models.BooleanField(default=False)),
                ('with_data', models.BooleanField(default=False)),
                ('train_available', models.BooleanField(default=False)),
            ],
        ),
    ]
