# Generated by Django 3.2 on 2021-04-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210409_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='section',
            field=models.CharField(choices=[('EA', 'Anubhuti Class(EA)'), ('1A', 'AC First Class(1A)'), ('EC', 'Exec. Chair Car(EC)'), ('2A', 'AC 2Tier (2A)'), ('FC', 'First CLass(FC)'), ('3A', 'AC 3 Tier(3A)'), ('3E', 'AC 3Economy (3E)'), ('CC', 'AC Chair car(CC)')], default='EA', max_length=50),
        ),
    ]
