# Generated by Django 3.1.7 on 2021-04-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210412_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='SEAT',
            new_name='seat',
        ),
    ]
