# Generated by Django 3.1.7 on 2021-04-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210412_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='d_from',
            field=models.CharField(default='Assam', max_length=50),
        ),
        migrations.AlterField(
            model_name='travel',
            name='d_to',
            field=models.CharField(default='Assam', max_length=50),
        ),
        migrations.AlterField(
            model_name='travel',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='travel',
            name='seat',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='travel',
            name='section',
            field=models.CharField(default='EA', max_length=200),
        ),
    ]
